name = "JSOSolvers"
uuid = "10dff2fc-5484-5881-a0e0-c90441020f8a"
version = "0.1.0"

[deps]
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SolverTools = "b5612192-2639-5dc1-abfe-fbedd65fab29"

[compat]
julia = "1"
Krylov = "≥ 0.3.0"
LinearOperators = "≥ 0.5.0"
NLPModels = "≥ 0.7.0"
SolverTools = "≥ 0.1.0"

[extras]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SparseArrays", "Test"]
