name = "JSOSolvers"
uuid = "10dff2fc-5484-5881-a0e0-c90441020f8a"
version = "0.12.1"

[deps]
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"
SolverParameters = "d076d87d-d1f9-4ea3-a44b-64b4cdd1e470"
SolverTools = "b5612192-2639-5dc1-abfe-fbedd65fab29"

[compat]
Krylov = "0.9.6"
LinearOperators = "2.0"
NLPModels = "0.21"
NLPModelsModifiers = "0.7"
SolverCore = "0.3"
SolverParameters = "0.1"
SolverTools = "0.9"
julia = "1.6"

[extras]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
NLPModelsTest = "7998695d-6960-4d3a-85c4-e1bceb8cd856"
SolverTest = "4343dc35-3317-4c6e-8877-f0cc8502c90e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ADNLPModels", "NLPModelsTest", "SolverTest", "SparseArrays", "Test"]
