[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUTEst = "1b53aba6-35b6-5f92-a507-53c67d53f819"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ExaModels = "1037b233-b668-4ce9-9b63-f9f681f55dd2"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSOSolvers = "10dff2fc-5484-5881-a0e0-c90441020f8a"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
NLPModelsTest = "7998695d-6960-4d3a-85c4-e1bceb8cd856"
OptimizationProblems = "5049e819-d29b-5fba-b941-0eee7e64c1c6"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SolverBenchmark = "581a75fa-a23a-52d0-a590-d6201de2218a"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"

[compat]
Documenter = "1.0"
